[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spatio-flux"
version = "1.1.0"
description = "A demonstration of process composition rebuilding and extending COMETS by composing functional components"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "bigraph-schema>=1.2.4",
    "process-bigraph>=1.2.2",
    "bigraph-viz>=1.1.0",
    "cobra",
    "imageio",
    "ipython",
    "matplotlib",
    "pymunk",
    "scipy",
]

[dependency-groups]
dev = [
    "build",
    "pytest",
]

# Make sure all subpackages are included
[tool.setuptools.packages.find]
where = ["."]
include = ["spatio_flux*"]
exclude = ["tests*", "docs*"]
