#!/usr/bin/env python
"""Build a static, self-contained PAPER-FIGURES page for the read-only site.

The read-only workbench snapshot (vivarium-workbench-publish) only captures the
runtime visualizations it re-renders from runs.db; the paper figures are STATIC
images produced by the figure pipeline (a headless loom render) and committed to
the repo, so they never make it into that snapshot. This publishes them directly:

  <out>/index.html         — a gallery of every stitched figure (fig 1-8), each
                             linking its full-res SVG + PNG
  <out>/paper-figures.zip  — the complete downloadable bundle (panels + finals)
  <out>/<figure_*.svg|png> — the individual figure files

Deployed to gh-pages under figures/ alongside report/ and workbench/, and linked
from the test-suite report + README, so the paper figures are viewable and
downloadable on the read-only site.

    python scripts/build_figures_site.py [workspace=.] [out=figures-site]
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

INV = "paper-figures"


def _zip(ws: Path, out: Path) -> int:
    """Write the investigation figures bundle via the workbench helper (best-
    effort — the page still builds from the committed files if it's unavailable)."""
    try:
        from vivarium_workbench.lib.investigation_figures import build_figures_zip
        blob = build_figures_zip(str(ws), INV)
        if blob:
            (out / "paper-figures.zip").write_bytes(blob)
            return len(blob)
    except Exception as e:  # noqa: BLE001
        print(f"  (figures.zip skipped: {type(e).__name__}: {e})")
    return 0


def _sort_key(p: Path):
    # figure_1, figure_2a, figure_2b, figure_3, … → (number, suffix)
    stem = p.stem.replace("figure_", "")
    num = "".join(c for c in stem if c.isdigit())
    suf = "".join(c for c in stem if not c.isdigit())
    return (int(num) if num else 99, suf)


def main() -> None:
    ws = Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    out = Path(sys.argv[2] if len(sys.argv) > 2 else "figures-site")
    out.mkdir(parents=True, exist_ok=True)

    nbytes = _zip(ws, out)

    figs = sorted(ws.glob("studies/fig-*/visualizations/figure_*.png"), key=_sort_key)
    cards = []
    for png in figs:
        svg = png.with_suffix(".svg")
        shutil.copy(png, out / png.name)
        if svg.is_file():
            shutil.copy(svg, out / svg.name)
        label = png.stem.replace("figure_", "Figure ")
        links = f'<a href="{svg.name}">SVG</a> · <a href="{png.name}">PNG</a>' if svg.is_file() \
            else f'<a href="{png.name}">PNG</a>'
        cards.append(
            f'<figure class="fig"><a href="{svg.name if svg.is_file() else png.name}">'
            f'<img src="{png.name}" loading="lazy" alt="{label}"></a>'
            f'<figcaption><b>{label}</b> — {links}</figcaption></figure>')

    dl = (f'<p class="dl"><a class="btn" href="paper-figures.zip">⬇ Download all figures '
          f'({nbytes // 1024 // 1024} MB zip)</a></p>') if nbytes else ""
    html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Process Bigraph — paper figures</title>
<style>
  :root {{ color-scheme: light dark; }}
  body {{ font-family: -apple-system, system-ui, sans-serif; margin: 0 auto; max-width: 1100px;
         padding: 28px 20px 60px; line-height: 1.5; }}
  h1 {{ font-size: 1.5rem; margin: 0 0 4px; }}
  .sub {{ color: #64748b; margin: 0 0 20px; }}
  .btn {{ display: inline-block; background: #1b9e77; color: #fff; text-decoration: none;
          padding: 8px 16px; border-radius: 8px; font-weight: 600; }}
  .grid {{ display: grid; grid-template-columns: 1fr; gap: 28px; margin-top: 24px; }}
  .fig {{ margin: 0; border: 1px solid #e2e8f0; border-radius: 12px; padding: 14px; }}
  .fig img {{ width: 100%; height: auto; display: block; border-radius: 6px; }}
  figcaption {{ margin-top: 10px; font-size: .95rem; color: #334155; }}
  a {{ color: #2563eb; }}
</style></head><body>
<h1>Process Bigraph — paper figures</h1>
<p class="sub">Figures 1–8 from the paper-figures investigation, generated by the
reproducible figure pipeline. <a href="../report/index.html">Test-suite report</a> ·
<a href="../workbench/index.html">Read-only workbench</a></p>
{dl}
<div class="grid">
{''.join(cards)}
</div>
</body></html>"""
    (out / "index.html").write_text(html, encoding="utf-8")
    print(f"wrote {out}/index.html — {len(figs)} figures"
          + (f" + paper-figures.zip ({nbytes // 1024 // 1024} MB)" if nbytes else ""))


if __name__ == "__main__":
    main()
